//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Properties {
    using System ;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add2 {
            get {
                object obj = ResourceManager.GetObject("add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddItem {
            get {
                object obj = ResourceManager.GetObject("AddItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addUngVien {
            get {
                object obj = ResourceManager.GetObject("addUngVien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackGround_NS {
            get {
                object obj = ResourceManager.GetObject("BackGround_NS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bonhiem {
            get {
                object obj = ResourceManager.GetObject("bonhiem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Canhan {
            get {
                object obj = ResourceManager.GetObject("Canhan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChamCong {
            get {
                object obj = ResourceManager.GetObject("ChamCong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checked1 {
            get {
                object obj = ResourceManager.GetObject("checked1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChucDanh {
            get {
                object obj = ResourceManager.GetObject("ChucDanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChucDanh1 {
            get {
                object obj = ResourceManager.GetObject("ChucDanh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChuyenNganh {
            get {
                object obj = ResourceManager.GetObject("ChuyenNganh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeShutdown {
            get {
                object obj = ResourceManager.GetObject("closeShutdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Copy_of_Save {
            get {
                object obj = ResourceManager.GetObject("Copy_of_Save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decision {
            get {
                object obj = ResourceManager.GetObject("decision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documents {
            get {
                object obj = ResourceManager.GetObject("documents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Duoi {
            get {
                object obj = ResourceManager.GetObject("Duoi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_48 {
            get {
                object obj = ResourceManager.GetObject("Excel_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_edit {
            get {
                object obj = ResourceManager.GetObject("Excel_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_edit2 {
            get {
                object obj = ResourceManager.GetObject("Excel_edit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hinh1 {
            get {
                object obj = ResourceManager.GetObject("hinh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hinhnenchinh {
            get {
                object obj = ResourceManager.GetObject("hinhnenchinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HopDong {
            get {
                object obj = ResourceManager.GetObject("HopDong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Huyen {
            get {
                object obj = ResourceManager.GetObject("Huyen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap huyen1 {
            get {
                object obj = ResourceManager.GetObject("huyen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeHoach2 {
            get {
                object obj = ResourceManager.GetObject("KeHoach2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeHoachChiTiet {
            get {
                object obj = ResourceManager.GetObject("KeHoachChiTiet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeHoachTD1 {
            get {
                object obj = ResourceManager.GetObject("KeHoachTD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeHoachXetDuyet {
            get {
                object obj = ResourceManager.GetObject("KeHoachXetDuyet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lcd {
            get {
                object obj = ResourceManager.GetObject("lcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login1 {
            get {
                object obj = ResourceManager.GetObject("login1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login2 {
            get {
                object obj = ResourceManager.GetObject("login2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Luong {
            get {
                object obj = ResourceManager.GetObject("Luong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LyDo {
            get {
                object obj = ResourceManager.GetObject("LyDo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainmain {
            get {
                object obj = ResourceManager.GetObject("mainmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi!!!.
        /// </summary>
        internal static string MessageBox_Error_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MessageBox_Message_Title {
            get {
                return ResourceManager.GetString("MessageBox_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string MessageBox_Question_Title {
            get {
                return ResourceManager.GetString("MessageBox_Question_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo!!!.
        /// </summary>
        internal static string MessageBox_Warning_Title {
            get {
                return ResourceManager.GetString("MessageBox_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình xảy ra lỗi. Vui lòng liên hệ tác giả.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập {0}..
        /// </summary>
        internal static string MSG002 {
            get {
                return ResourceManager.GetString("MSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} và {1} không đúng. Vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG003 {
            get {
                return ResourceManager.GetString("MSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa..
        /// </summary>
        internal static string MSG004 {
            get {
                return ResourceManager.GetString("MSG004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được bỏ trống..
        /// </summary>
        internal static string MSG005 {
            get {
                return ResourceManager.GetString("MSG005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn xóa..
        /// </summary>
        internal static string MSG006 {
            get {
                return ResourceManager.GetString("MSG006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công..
        /// </summary>
        internal static string MSG007 {
            get {
                return ResourceManager.GetString("MSG007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại..
        /// </summary>
        internal static string MSG008 {
            get {
                return ResourceManager.GetString("MSG008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        internal static string MSG009 {
            get {
                return ResourceManager.GetString("MSG009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu dữ liệu thay đổi..
        /// </summary>
        internal static string MSG010 {
            get {
                return ResourceManager.GetString("MSG010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi dữ liệu vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG011 {
            get {
                return ResourceManager.GetString("MSG011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang sử dụng không thể xóa..
        /// </summary>
        internal static string MSG012 {
            get {
                return ResourceManager.GetString("MSG012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại nhân viên này..
        /// </summary>
        internal static string MSG013 {
            get {
                return ResourceManager.GetString("MSG013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình đang chạy. Không thể chạy nhiều phiên bản cùng lúc..
        /// </summary>
        internal static string MSG014 {
            get {
                return ResourceManager.GetString("MSG014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập {0}..
        /// </summary>
        internal static string MSG015 {
            get {
                return ResourceManager.GetString("MSG015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập không đúng.
        /// </summary>
        internal static string MSG016 {
            get {
                return ResourceManager.GetString("MSG016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn hoặc bằng {1}..
        /// </summary>
        internal static string MSG017 {
            get {
                return ResourceManager.GetString("MSG017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải lưu trước khi thêm thông tin chi tiết..
        /// </summary>
        internal static string MSG018 {
            get {
                return ResourceManager.GetString("MSG018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có kế hoạch cho quý {0}..
        /// </summary>
        internal static string MSG019 {
            get {
                return ResourceManager.GetString("MSG019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn  {1}..
        /// </summary>
        internal static string MSG020 {
            get {
                return ResourceManager.GetString("MSG020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt cho phiếu yêu cầu này..
        /// </summary>
        internal static string MSG021 {
            get {
                return ResourceManager.GetString("MSG021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để xuất.
        /// </summary>
        internal static string MSG022 {
            get {
                return ResourceManager.GetString("MSG022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở file vừa xuất ?.
        /// </summary>
        internal static string MSG023 {
            get {
                return ResourceManager.GetString("MSG023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sẽ được tạo ra khi lưu..
        /// </summary>
        internal static string MSG024 {
            get {
                return ResourceManager.GetString("MSG024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nhỏ hơn  {1}..
        /// </summary>
        internal static string MSG025 {
            get {
                return ResourceManager.GetString("MSG025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang sử dụng không thể xóa..
        /// </summary>
        internal static string MSG026 {
            get {
                return ResourceManager.GetString("MSG026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu nhân viên này.
        /// </summary>
        internal static string MSG027 {
            get {
                return ResourceManager.GetString("MSG027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã lên chương trình thử việc! Không thể xóa!.
        /// </summary>
        internal static string MSG028 {
            get {
                return ResourceManager.GetString("MSG028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy biểu mẫu!.
        /// </summary>
        internal static string MSG029 {
            get {
                return ResourceManager.GetString("MSG029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian phải nằm trong quý {0}..
        /// </summary>
        internal static string MSG030 {
            get {
                return ResourceManager.GetString("MSG030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên {0} chưa có hình, vui lòng kiểm tra lại!.
        /// </summary>
        internal static string MSG031 {
            get {
                return ResourceManager.GetString("MSG031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sẽ được tạo khi bổ nhiệm..
        /// </summary>
        internal static string MSG032 {
            get {
                return ResourceManager.GetString("MSG032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng viên {0} đã được bổ nhiệm..
        /// </summary>
        internal static string MSG033 {
            get {
                return ResourceManager.GetString("MSG033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chấm công cho nhân viên này !.
        /// </summary>
        internal static string MSG034 {
            get {
                return ResourceManager.GetString("MSG034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu tháng {0} năm {1} đã được đỗ..
        /// </summary>
        internal static string MSG035 {
            get {
                return ResourceManager.GetString("MSG035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạm ứng cho tháng {0}..
        /// </summary>
        internal static string MSG036 {
            get {
                return ResourceManager.GetString("MSG036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tính lương cho tháng {0}..
        /// </summary>
        internal static string MSG037 {
            get {
                return ResourceManager.GetString("MSG037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn thật sự muốn khóa lương ? .
        /// </summary>
        internal static string MSG038 {
            get {
                return ResourceManager.GetString("MSG038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương tháng {0} đã bị khóa..
        /// </summary>
        internal static string MSG039 {
            get {
                return ResourceManager.GetString("MSG039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xem {0} của người khác..
        /// </summary>
        internal static string MSG040 {
            get {
                return ResourceManager.GetString("MSG040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập {0} hoặc {1}..
        /// </summary>
        internal static string MSG041 {
            get {
                return ResourceManager.GetString("MSG041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đỗ dữ liệu thành công..
        /// </summary>
        internal static string MSG042 {
            get {
                return ResourceManager.GetString("MSG042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có quyết định thôi việc cho nhân viên này..
        /// </summary>
        internal static string MSG043 {
            get {
                return ResourceManager.GetString("MSG043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể tính lương cho tháng thôi việc có hiệu lực vui lòng kiểm tra ngày hiệu lực của quyết định thôi việc..
        /// </summary>
        internal static string MSG044 {
            get {
                return ResourceManager.GetString("MSG044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu {0}..
        /// </summary>
        internal static string MSG045 {
            get {
                return ResourceManager.GetString("MSG045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương tháng {0} năm {1} đã bị khóa vui lòng chọn ngày hiệu lực vào tháng khác..
        /// </summary>
        internal static string MSG046 {
            get {
                return ResourceManager.GetString("MSG046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi nhân viên chỉ có 1 hợp đồng {0}..
        /// </summary>
        internal static string MSG047 {
            get {
                return ResourceManager.GetString("MSG047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối tới cơ sở dữ liệu. Vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG048 {
            get {
                return ResourceManager.GetString("MSG048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian phải nằm trong năm {0}..
        /// </summary>
        internal static string MSG049 {
            get {
                return ResourceManager.GetString("MSG049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng thử việc chưa kết thúc..
        /// </summary>
        internal static string MSG050 {
            get {
                return ResourceManager.GetString("MSG050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng hiện tại chưa kết thúc..
        /// </summary>
        internal static string MSG051 {
            get {
                return ResourceManager.GetString("MSG051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu yêu cầu tương tự đã có bạn phải chỉnh sửa hoặc đề xuất tăng số lượng..
        /// </summary>
        internal static string MSG052 {
            get {
                return ResourceManager.GetString("MSG052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang đăng nhập vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG053 {
            get {
                return ResourceManager.GetString("MSG053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công..
        /// </summary>
        internal static string MSG054 {
            get {
                return ResourceManager.GetString("MSG054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại..
        /// </summary>
        internal static string MSG055 {
            get {
                return ResourceManager.GetString("MSG055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở dữ liệu không phù hợp!Vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG056 {
            get {
                return ResourceManager.GetString("MSG056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không cố quyền ghi trên thư mục cài đặt của ứng dụng!Vui lòng kiểm tra lại..
        /// </summary>
        internal static string MSG057 {
            get {
                return ResourceManager.GetString("MSG057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng khởi động lại ứng dụng..
        /// </summary>
        internal static string MSG058 {
            get {
                return ResourceManager.GetString("MSG058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm ứng không vượt quá 1/2 lương cơ bản..
        /// </summary>
        internal static string MSG059 {
            get {
                return ResourceManager.GetString("MSG059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NgoaiNgu {
            get {
                object obj = ResourceManager.GetObject("NgoaiNgu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nha {
            get {
                object obj = ResourceManager.GetObject("Nha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhansu {
            get {
                object obj = ResourceManager.GetObject("nhansu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password {
            get {
                object obj = ResourceManager.GetObject("password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Person {
            get {
                object obj = ResourceManager.GetObject("Person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Phai {
            get {
                object obj = ResourceManager.GetObject("Phai", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhieuYeuCau {
            get {
                object obj = ResourceManager.GetObject("PhieuYeuCau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhieuYeuCau1 {
            get {
                object obj = ResourceManager.GetObject("PhieuYeuCau1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhieuYeuCau3 {
            get {
                object obj = ResourceManager.GetObject("PhieuYeuCau3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhongBan {
            get {
                object obj = ResourceManager.GetObject("PhongBan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhongBan1 {
            get {
                object obj = ResourceManager.GetObject("PhongBan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhongBan2 {
            get {
                object obj = ResourceManager.GetObject("PhongBan2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PhuCap {
            get {
                object obj = ResourceManager.GetObject("PhuCap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer1 {
            get {
                object obj = ResourceManager.GetObject("printer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer5 {
            get {
                object obj = ResourceManager.GetObject("Printer5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer6 {
            get {
                object obj = ResourceManager.GetObject("Printer6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Process {
            get {
                object obj = ResourceManager.GetObject("Process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap process1 {
            get {
                object obj = ResourceManager.GetObject("process1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quanHe {
            get {
                object obj = ResourceManager.GetObject("quanHe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quanlyquyetdinh {
            get {
                object obj = ResourceManager.GetObject("quanlyquyetdinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Relative {
            get {
                object obj = ResourceManager.GetObject("Relative", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resetpassword {
            get {
                object obj = ResourceManager.GetObject("resetpassword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resrt {
            get {
                object obj = ResourceManager.GetObject("resrt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save3 {
            get {
                object obj = ResourceManager.GetObject("save3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save4 {
            get {
                object obj = ResourceManager.GetObject("save4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search2 {
            get {
                object obj = ResourceManager.GetObject("Search2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shutdowns {
            get {
                object obj = ResourceManager.GetObject("shutdowns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý....
        /// </summary>
        internal static string STATUS_PROCESSING {
            get {
                return ResourceManager.GetString("STATUS_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật....
        /// </summary>
        internal static string STATUS_UPDATING {
            get {
                return ResourceManager.GetString("STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tacGia {
            get {
                object obj = ResourceManager.GetObject("tacGia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThongBao {
            get {
                object obj = ResourceManager.GetObject("ThongBao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThuViec {
            get {
                object obj = ResourceManager.GetObject("ThuViec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThuViec1 {
            get {
                object obj = ResourceManager.GetObject("ThuViec1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThuViec2 {
            get {
                object obj = ResourceManager.GetObject("ThuViec2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tinh {
            get {
                object obj = ResourceManager.GetObject("Tinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToChuc {
            get {
                object obj = ResourceManager.GetObject("ToChuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TonGiao {
            get {
                object obj = ResourceManager.GetObject("TonGiao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Trai {
            get {
                object obj = ResourceManager.GetObject("Trai", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Tren {
            get {
                object obj = ResourceManager.GetObject("Tren", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TuyenDung {
            get {
                object obj = ResourceManager.GetObject("TuyenDung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UngVien {
            get {
                object obj = ResourceManager.GetObject("UngVien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user1 {
            get {
                object obj = ResourceManager.GetObject("user1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserGroup {
            get {
                object obj = ResourceManager.GetObject("UserGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserToGroup {
            get {
                object obj = ResourceManager.GetObject("UserToGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap useruser {
            get {
                object obj = ResourceManager.GetObject("useruser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViTinh {
            get {
                object obj = ResourceManager.GetObject("ViTinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap website51 {
            get {
                object obj = ResourceManager.GetObject("website51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap weding {
            get {
                object obj = ResourceManager.GetObject("weding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Word {
            get {
                object obj = ResourceManager.GetObject("Word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XetDuyet {
            get {
                object obj = ResourceManager.GetObject("XetDuyet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XetDuyetKH {
            get {
                object obj = ResourceManager.GetObject("XetDuyetKH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YeuCauCongViec {
            get {
                object obj = ResourceManager.GetObject("YeuCauCongViec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
